// SPDX-FileCopyrightText: Copyright (c) 2021-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! CUDA toolkit bindings with dynamic library loading.
//!
//! Types, enums, and constants are generated at build time from CUDA headers
//! via `bindgen`. The CUDA driver (`libcuda`) and cuRAND (`libcurand`)
//! libraries are loaded **dynamically at runtime** via `libloading`, so they
//! do not need to be present at build time.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

// Types, enums, and constants generated by bindgen (no function declarations).
include!(concat!(env!("OUT_DIR"), "/types.rs"));

#[inline]
pub fn set_mem_location_id(loc: &mut CUmemLocation, id: ::core::ffi::c_int) {
    #[cfg(cu_mem_location_anon_union)]
    {
        loc.__bindgen_anon_1.id = id;
    }
    #[cfg(not(cu_mem_location_anon_union))]
    {
        loc.id = id;
    }
}

#[allow(dead_code)]
mod generated_cuda {
    use super::*;
    include!(concat!(env!("OUT_DIR"), "/cuda_driver_api.rs"));
}

#[allow(dead_code)]
mod generated_curand {
    use super::*;
    include!(concat!(env!("OUT_DIR"), "/curand_api.rs"));
}

// Dynamic loading of CUDA driver and cuRAND function symbols.
mod dyn_load;
pub use dyn_load::*;

pub fn cuda_toolkit_dir() -> String {
    env!("CUTILE_RESOLVED_CUDA_TOOLKIT_PATH").to_string()
}

/// Reports the elapsed time in milliseconds between two recorded events.
///
/// CUDA 12.8 renamed the driver entry point to `cuEventElapsedTime_v2`; this
/// crate's minimum supported toolkit (13.2) always declares the `_v2` symbol,
/// so this helper dispatches to it directly. It exists for source
/// compatibility with cuda-oxide's bindings, which expose the same helper.
///
/// # Safety
///
/// Same contract as the underlying driver call: `elapsed_ms` must be valid
/// for an `f32` write, and `start`/`end` must be valid event handles recorded
/// in the current context.
pub unsafe fn cu_event_elapsed_time(
    elapsed_ms: *mut f32,
    start: CUevent,
    end: CUevent,
) -> CUresult {
    unsafe { cuEventElapsedTime_v2(elapsed_ms, start, end) }
}

#[cfg(test)]
mod cuda_tests {
    use super::*;
    use std::ffi::{c_int, c_ulonglong};
    use std::mem::MaybeUninit;

    fn init() -> (CUdevice, CUcontext) {
        unsafe {
            let init_res = crate::cuInit(0);
            assert_eq!(init_res, 0, "init failed");

            let mut dev: MaybeUninit<crate::CUdevice> = MaybeUninit::uninit();
            let dev_result = crate::cuDeviceGet(dev.as_mut_ptr(), 0 as c_int);
            assert_eq!(dev_result, 0, "get device failed");
            let dev = dev.assume_init();

            let mut ctx = MaybeUninit::uninit();
            let ctx_res = crate::cuDevicePrimaryCtxRetain(ctx.as_mut_ptr(), dev);
            assert_eq!(ctx_res, 0, "retain context failed");
            let ctx = ctx.assume_init();
            assert_eq!(
                crate::cuCtxSetCurrent(ctx),
                0,
                "failed to set current context"
            );
            (dev, ctx)
        }
    }

    unsafe fn get_dptr(bytesize: usize) -> CUdeviceptr {
        let mut dptr: MaybeUninit<CUdeviceptr> = MaybeUninit::uninit();
        assert!(cuMemAlloc_v2(dptr.as_mut_ptr(), bytesize) == 0);
        dptr.assume_init()
    }

    unsafe fn get_rng() -> curandGenerator_t {
        let mut curand_gen_uninited: MaybeUninit<curandGenerator_t> = MaybeUninit::uninit();
        let curand_rng_type = curandRngType_CURAND_RNG_PSEUDO_DEFAULT;
        assert!(curandCreateGenerator(curand_gen_uninited.as_mut_ptr(), curand_rng_type) == 0);
        curand_gen_uninited.assume_init()
    }

    unsafe fn set_seed(gen: curandGenerator_t, seed: u64) {
        assert!(curandSetPseudoRandomGeneratorSeed(gen, c_ulonglong::from(seed)) == 0);
    }

    #[test]
    fn cu_event_elapsed_time_helper_signature() {
        // Compile-time check that the helper keeps the signature cuda-oxide's
        // bindings expose.
        let _: unsafe fn(*mut f32, CUevent, CUevent) -> CUresult = cu_event_elapsed_time;
    }

    #[test]
    fn test_curand() {
        unsafe {
            let (_dev, _ctx) = init();
            let curand_gen = get_rng();
            set_seed(curand_gen, 123);
            let num_elements = 32;
            let bytesize = num_elements * size_of::<f32>();
            let dptr = get_dptr(bytesize);
            assert!(
                curandGenerateNormal(curand_gen, dptr as *mut f32, num_elements, 0.0, 1.0) == 0
            );
            assert!(curandDestroyGenerator(curand_gen) == 0);
            assert!(cuMemFree_v2(dptr) == 0);
        }
    }
}
