[package]
name = "cutile-compiler"
description = "Crate for compiling kernels authored in cuTile Rust to executable kernels."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["cutile", "compiler", "gpu"]

[features]
default = []

[dependencies]
uuid = { workspace = true }
sha2 = { workspace = true }
cuda-core = { workspace = true }
cuda-async = { workspace = true }
cutile-ir = { workspace = true }
cutile-frontend = { workspace = true }

[lints]
workspace = true
