[package]
name = "cutile-frontend"
description = "cuTile Rust compiler frontend. Rust DSL modules to Tile IR."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords = ["cutile", "compiler", "frontend"]

[dependencies]
syn = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
regex = { workspace = true }
prettyplease = { workspace = true }
half = { workspace = true }
anyhow = { workspace = true }
stacker = { workspace = true }
linkme = { workspace = true }
cutile-ir = { workspace = true }
cutile-obligation = { workspace = true }
cutile-syn-utils = { workspace = true }

[lints]
workspace = true
